query { deliveryProfiles(first: 10) { nodes { id name default originLocationCount activeMethodDefinitionsCount profileLocationGroups { locationGroup { id locations(first:5){ nodes { name address { city province country } } } } locationGroupZones(first: 20) { nodes { zone { id name countries { name code { countryCode restOfWorld } provinces { name code } } } methodDefinitions(first: 20) { nodes { id name active description rateProvider { __typename ... on DeliveryRateDefinition { id price { amount currencyCode } } ... on DeliveryParticipant { id fixedFee { amount currencyCode } percentageOfRateFee participantServices { name active } } } methodConditions { field operator conditionCriteria { __typename ... on MoneyV2 { amount currencyCode } ... on Weight { value unit } } } } } } } } } } }